docs: Update example to show how to pass additional permissions and policies to the tasks role
terraform-aws-modules/terraform-aws-ecs pull request #115
Opened 2023-09-21 14:15 UTC by bryantbiggs

## Description
- Update example to show how to pass additional permissions and policies to the tasks role

## Motivation and Context
- Resolves #114

## Breaking Changes
- No

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

![image](https://github.com/terraform-aws-modules/terraform-aws-ecs/assets/10913471/190fb046-e800-414f-a74c-b2318c8e2142)

2023-09-21 14:47 UTC, antonbabenko requested changes

2023-09-21 14:47 UTC, antonbabenko commented on examples/complete/main.tf
> +          actions   = ["s3:List"]
```suggestion
          actions   = ["s3:List*"]
```
List what?

2023-10-30 14:08 UTC, bryantbiggs commented
@antonbabenko if you get time for a second look 🙏🏽

2023-10-30 14:36 UTC, antonbabenko approved these changes

2023-10-30 14:37 UTC, merged

2023-10-30 15:42 UTC, antonbabenko commented
This PR is included in version 5.3.0 :tada: