feat: Support `managed_draining` argument at `aws_ecs_capacity_provider` resource
terraform-aws-modules/terraform-aws-ecs pull request #158
Opened 2024-01-26 15:45 UTC by ivan-sukhomlyn

## Description
Support of `managed_draining` argument at `auto_scaling_group_provider` block of  `aws_ecs_capacity_provider` resource introduced by
- [v5.34.0 of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/v5.34.0/CHANGELOG.md).
- https://github.com/hashicorp/terraform-provider-aws/pull/35421

## Motivation and Context
- Resolves https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/156

## Breaking Changes
**No**

:warning: Minimal required AWS provider version is `>=5.34.0`

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

For already created ECS ASG capacity provider:
config:
```HCL
module "ecs_cluster" {
  source = "../../../../../../open-source/terraform-aws-ecs/modules/cluster"

  cluster_name = local.ecs_cluster_name

  # Capacity provider - autoscaling groups
  default_capacity_provider_use_fargate = false

  autoscaling_capacity_providers = {
    for k, v in module.asg_ecs : "${local.ecs_cluster_name}-${k}" => {
      auto_scaling_group_arn         = v.autoscaling_group_arn
      managed_draining               = "ENABLED"
# ....
}
```

```bash
$ terraform init -upgrade && terraform plan
...
- Installing hashicorp/aws v5.34.0...
- Installed hashicorp/aws v5.34.0 (signed by HashiCorp)
...

  # module.ecs_cluster.aws_ecs_capacity_provider.this["xxxxx"] will be updated in-place
  ~ resource "aws_ecs_capacity_provider" "this" {
        id       = "arn:aws:ecs:xxx:xxx:capacity-provider/xxxxx"
        name     = "xxxx"

        # (2 unchanged attributes hidden)

      ~ auto_scaling_group_provider {
          ~ managed_draining               = "DISABLED" -> "ENABLED"
            # (2 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }
```
- [x] I have executed `pre-commit run -a` on my pull request
```
✗ pre-commit run -a
Terraform fmt............................................................Passed
Terraform wrapper with for_each in module................................Passed
Terraform validate.......................................................Passed
Terraform docs...........................................................Passed
Terraform validate with tflint...........................................Passed
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
```

2024-01-26 16:06 UTC, bryantbiggs requested changes
this is a breaking change - we have a few other breaking changes batched up now so we should do them all at once

also - the version would need to be aligned across the project

2024-01-26 16:36 UTC, ivan-sukhomlyn commented
@bryantbiggs should I do something additionally from my side in that case?

2024-01-29 16:31 UTC, remiflament commented
yes @ivan-sukhomlyn the `versions.tf` should be the same in all the project. So it needs to be update in all the other submodules.

2024-01-29 18:07 UTC, ivan-sukhomlyn commented
oops!
@remiflament thank you for the clarification 👍 🙂

2024-02-12 15:42 UTC, bryantbiggs approved these changes
Thank you! Merging this into the `wip/v6` branch

2024-02-12 15:43 UTC, merged