feat: Add option to ignore `load_balancer` changes to ECS service
terraform-aws-modules/terraform-aws-ecs pull request #81
Opened 2023-05-02 13:59 UTC by gpdenny

## Description
Create (another :grimacing:) instance of `aws_ecs_service` to allow users to ignore `load_balancer` changes.

## Motivation and Context
I understand this pattern could be never ending, and result in a module that's very difficult to maintain, but to me it feels like a fairly typical use-case to support Codedeploy with Blue/Green deployment.

I'm not sure if maybe it should be a single variable that controls this, instead of setting both `ignore_task_definition_changes` and `ignore_load_balancer_changes` to true?

## Breaking Changes
No breaking changes, default behaviour is unchanged.

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- Tested all three scenarios where each of the instances of `aws_ecs_service` are used.
- [x] I have executed `pre-commit run -a` on my pull request

2023-05-02 20:40 UTC, antonbabenko requested changes
Looks pretty good. Please update `main.tf` in the root module to include the same variables.

2023-05-02 20:40 UTC, antonbabenko commented on modules/service/outputs.tf
> +  value       = try(aws_ecs_service.this[0].name, aws_ecs_service.ignore_task_definition[0].name, aws_ecs_service.ignore_task_definition_load_balancer[0].name, null)
A similar change should be implemented for output `id`.

2023-05-02 20:40 UTC, antonbabenko commented on docs/README.md
> +
```suggestion
```

2023-05-03 00:51 UTC, bryantbiggs commented
I think I am more inclined to add this to the `ignore_task_definition` version of the service rather than create yet another service definition. we can just add the `load_balancer` attribute to the ignore list [here](https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/0f941dfd0dde2c13a2e9af0593ec84af4e3c1ef8/modules/service/main.tf#L391), update the docs, and then we can show in the docs a similar hack like that of updating the service desired count https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/docs/README.md#service-1 

So one service is static, all controlled in Terraform, the other one is dynamic for changing values

2023-05-03 09:48 UTC, gpdenny commented
Agree @bryantbiggs this sounds less likely for things to get out of hand in future :joy: 
Should we rename the `ignore_task_definition` instance as well if we are adding more to the ignore list? Any preference?

2023-05-15 14:38 UTC, bryantbiggs commented
we don't need to rename it at this time since that will be a breaking change. Lets just ensure its properly documented

2023-06-02 16:53 UTC, david1437 commented
Hi, this feature is very important for my company's use case is there any way I can help to move this forward?

2023-06-03 07:58 UTC, gpdenny commented
Hey @david1437 I've been distracted changing day jobs, but I'll still need this in my new role. 
Hoping to tackle some point next week :ok_hand:

2023-06-03 12:04 UTC, bryantbiggs approved these changes

2023-06-03 12:05 UTC, bryantbiggs commented
@antonbabenko let me know what you think

2023-06-05 17:26 UTC, antonbabenko approved these changes

2023-06-05 17:26 UTC, antonbabenko commented on docs/README.md
> +    name     = each.key
```suggestion
    name = each.key
```

2023-06-05 17:54 UTC, merged